# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f631e64261daf1f181c8fbb0f9e1a69ca20c85249bc256bf5b1bc29bd8bbe45e27c0a66f59ea35b9cbbb2fdeb67fe76315238510fa5b0c5a75b9b60d0a426bb5

test:
  secret_key_base: 505230cc5a0ae15d8f60e716debd1ca97efc50ecb3f4567e372bcaf9317880ca29296d7abd0428e2d930cad748ee7f8717dd72437da92372cf667ee14b4d1603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
